# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
services:
  generator:
    image: wazuh/wazuh-certs-generator:0.0.2
    hostname: wazuh-certs-generator
    # Uncomment the following lines if your environment requires an HTTP proxy
    # environment:
    #   - HTTP_PROXY=YOUR_PROXY_ADDRESS_OR_DNS
    volumes:
      - ./config/wazuh_indexer_ssl_certs/:/certificates/
      - ./config/certs.yml:/config/certs.yml
