# docker-compose.sensors.yml
# Sensors + log shipper, ready for injection into your Wazuh stack
# Images: zeek/zeek (official) | jasonish/suricata (maintained)

version: "3.9"

volumes:
  zeek-logs:          # mounted read-only in Filebeat/Wazuh agent
  suricata-logs:

networks:
  wazuh:              # reuses the network where your manager/indexer is already running
    external: true

services:
  zeek:
    env_file: .env
    image: zeek/zeek:latest
    container_name: zeek
    network_mode: host          # direct access to the sniffed interface
    volumes:
      - zeek-logs:/var/log/zeek
    command: >
      zeek -i ${IFACE:-eth0}
    restart: unless-stopped

  suricata:
    env_file: .env
    image: jasonish/suricata:7.0
    container_name: suricata
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - suricata-logs:/var/log/suricata
    command: >
      -i ${IFACE:-eth0} --af-packet=workers=4,cluster-id=99
    restart: unless-stopped

  filebeat:
    env_file: .env
    image: docker.elastic.co/beats/filebeat:7.17.25   # LTS version that Wazuh 5.x uses
    container_name: filebeat-sensors
    user: root
    network_mode: host
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro  # template below
      - zeek-logs:/var/log/zeek:ro
      - suricata-logs:/var/log/suricata:ro
    environment:
      - INDEXER_HOST=${WAZUH_INDEXER:-https://wazuh.indexer:9200}
      - INDEXER_USER=${INDEXER_USER:-admin}
      - INDEXER_PASS=${INDEXER_PASS:-SecretPassword}
    restart: unless-stopped
